### ISSUE TITLE
Optimize image assets

### ISSUE THREAD

**Issue by pdehaan** [raymak/vpn-recommendation-shield-study#16]
Related to #15, but we should also make sure we run all the images through imagemin (or something similar).
Currently it looks like we only have [src/privileged/vpnRecommender/content/images/image.png](https://github.com/raymak/vpn-recommendation-shield-study/blob/master/src/privileged/vpnRecommender/content/images/image.png) (113KB), but if I run it through imagemin, I can drop it down to 85KB (saving 28KB):

```sh
$ npx imagemin-cli src/privileged/vpnRecommender/content/images/*.png --out-dir=.

1 image minified
```

```sh
$ git grep image.png

src/privileged/vpnRecommender/content/doorhanger/doorhanger.html:            <img id="image" src="../images/image.png" />
```

**Comment by raymak** [comment]
I'll optimize the recently added assets
