### ISSUE TITLE
Unable to trigger experiment via captive-portal

### ISSUE THREAD

**Issue by devinreams** [raymak/vpn-recommendation-shield-study#20]
I switched to some new wifi networks and triggered captive portal at the macOS level. After "canceling" those detections I manually went to detectportal.firefox.com (Firefox never triggered the portal itself after a few minutes) and even without success (eg. presenting a portal to sign in) I didn't see any debug output suggesting I got to portal state or the addon was triggered.

This may be my system as something I'm unable to manually trigger, or the extension, I can't quite tell.

I was running this via `npm run start`.

<img width="1997" alt="screen shot 2018-08-21 at 12 20 38 pm" src="https://user-images.githubusercontent.com/49511/44421042-c49c5280-a53c-11e8-8a52-9f4640d48f95.png">

Text of the console log info/debug statements here:
<details>
shield-study-utils: loading web extension experiment study/api.js api.js:8224
shield-study-utils: constructed! api.js:8264
shield-study-utils: wanting guard api.js:3495
shield-study-utils: adding schemas [object Object]
api.js:3510
shield-study-utils: Ajv schemas 
Array(15) [ "http://json-schema.org/draft-07/schema", "http://json-schema.org/draft-04/schema", "NullableString", "NullableInteger", "NullableNumber", "studyTypesEnum", "weightedVariationObject", "weightedVariationsArray", "anEndingRequest", "onEndStudyResponse", … ]
api.js:3515
shield-study-utils: setting up! -- {"activeExperimentName":"vpn-recommendation-study@shield.mozilla.org","endings":{"user-disable":{"baseUrls":["https://qsurvey.mozilla.com/s3/Shield-Study-Example-Survey/?reason=user-disable"],"category":null,"exacturls":null,"fullname":null},"ineligible":{"baseUrls":[],"category":null,"exacturls":null,"fullname":null},"expired":{"baseUrls":["https://qsurvey.mozilla.com/s3/Shield-Study-Example-Survey/?reason=expired"],"category":null,"exacturls":null,"fullname":null},"used-often":{"baseUrls":["https://qsurvey.mozilla.com/s3/Shield-Study-Example-Survey/?reason=used-often"],"category":"ended-positive","exacturls":null,"fullname":null},"a-non-url-opening-ending":{"baseUrls":[],"category":"ended-neutral","exacturls":null,"fullname":null},"introduction-leave-study":{"baseUrls":["https://qsurvey.mozilla.com/s3/Shield-Study-Example-Survey/?reason=introduction-leave-study"],"category":"ended-negative","exacturls":null,"fullname":null}},"expire":{"days":14},"studyType":"shield","telemetry":{"removeTestingFlag":false,"send":true},"testing":{},"weightedVariations":[{"name":"captive-portal","weight":1}],"allowEnroll":true} api.js:3674
shield-study-utils: about to guard studySetup 
Object { activeExperimentName: "vpn-recommendation-study@shield.mozilla.org", endings: {…}, expire: {…}, studyType: "shield", telemetry: {…}, testing: {}, weightedVariations: (1) […], allowEnroll: true }
api.js:3519
shield-study-utils: _deterministicVariation 
Array [ {…} ]
api.js:3877
shield-study-utils: setting up: variation captive-portal api.js:3703
shield-study-utils: attempting firstSeen api.js:3894
shield-study-utils: telemetry in:  shield-study {"study_state":"enter"} api.js:4098
shield-study-utils: getting info api.js:3831
shield-study-utils: getVariation: {"name":"captive-portal","weight":1} api.js:3739
shield-study-utils: about to guard studyInfoObject 
Object { activeExperimentName: "vpn-recommendation-study@shield.mozilla.org", isFirstRun: true, firstRunTimestamp: null, variation: {…}, shieldId: "", delayInMinutes: null }
api.js:3519
shield-study-utils: telemetry INFO: {"activeExperimentName":"vpn-recommendation-study@shield.mozilla.org","isFirstRun":true,"firstRunTimestamp":null,"variation":{"name":"captive-portal","weight":1},"shieldId":"","delayInMinutes":null} api.js:4100
shield-study-utils: telemetry: {"version":3,"study_name":"vpn-recommendation-study@shield.mozilla.org","branch":"captive-portal","addon_version":"2.0.0","shield_version":"5.0.4","type":"shield-study","data":{"study_state":"enter"},"testing":true} api.js:4141
shield-study-utils: getting info api.js:3831
shield-study-utils: getVariation: {"name":"captive-portal","weight":1} api.js:3739
shield-study-utils: about to guard studyInfoObject 
Object { activeExperimentName: "vpn-recommendation-study@shield.mozilla.org", isFirstRun: true, firstRunTimestamp: 1534874138971, variation: {…}, shieldId: "", delayInMinutes: 20159.999983333335 }
api.js:3519
shield-study-utils: startup.  setting active. isFirstRun? true api.js:3944
shield-study-utils: getting info api.js:3831
shield-study-utils: getVariation: {"name":"captive-portal","weight":1} api.js:3739
shield-study-utils: about to guard studyInfoObject 
Object { activeExperimentName: "vpn-recommendation-study@shield.mozilla.org", isFirstRun: true, firstRunTimestamp: 1534874138971, variation: {…}, shieldId: "", delayInMinutes: 20159.99995 }
api.js:3519
shield-study-utils: marking TelemetryEnvironment vpn-recommendation-study@shield.mozilla.org captive-portal api.js:3909
shield-study-utils: telemetry in:  shield-study {"study_state":"installed"} api.js:4098
shield-study-utils: getting info api.js:3831
shield-study-utils: getVariation: {"name":"captive-portal","weight":1} api.js:3739
shield-study-utils: about to guard studyInfoObject 
Object { activeExperimentName: "vpn-recommendation-study@shield.mozilla.org", isFirstRun: true, firstRunTimestamp: 1534874138971, variation: {…}, shieldId: "", delayInMinutes: 20159.99986666667 }
api.js:3519
shield-study-utils: telemetry INFO: {"activeExperimentName":"vpn-recommendation-study@shield.mozilla.org","isFirstRun":true,"firstRunTimestamp":1534874138971,"variation":{"name":"captive-portal","weight":1},"shieldId":"","delayInMinutes":20159.99986666667} api.js:4100
shield-study-utils: telemetry: {"version":3,"study_name":"vpn-recommendation-study@shield.mozilla.org","branch":"captive-portal","addon_version":"2.0.0","shield_version":"5.0.4","type":"shield-study","data":{"study_state":"installed"},"testing":true} api.js:4141
shield-study-utils: getting info api.js:3831
shield-study-utils: getVariation: {"name":"captive-portal","weight":1} api.js:3739
shield-study-utils: about to guard studyInfoObject 
Object { activeExperimentName: "vpn-recommendation-study@shield.mozilla.org", isFirstRun: true, firstRunTimestamp: 1534874138971, variation: {…}, shieldId: "", delayInMinutes: 20159.999633333333 }
api.js:3519
shield-study-utils: api info: {"activeExperimentName":"vpn-recommendation-study@shield.mozilla.org","isFirstRun":true,"firstRunTimestamp":1534874138971,"variation":{"name":"captive-portal","weight":1},"shieldId":"","delayInMinutes":20159.999633333333} api.js:8408
shield-study-utils: getting info api.js:3831
shield-study-utils: getVariation: {"name":"captive-portal","weight":1} api.js:3739
shield-study-utils: about to guard studyInfoObject 
Object { activeExperimentName: "vpn-recommendation-study@shield.mozilla.org", isFirstRun: true, firstRunTimestamp: 1534874138971, variation: {…}, shieldId: "", delayInMinutes: 20159.9996 }
api.js:3519
shield-study-utils: called sendTelemetry payload api.js:8498
shield-study-utils: telemetry {"message_type":"event","event":"study-start"} api.js:4166
shield-study-utils: telemetry in:  shield-study-addon {"attributes":{"message_type":"event","event":"study-start"}} api.js:4098
shield-study-utils: getting info api.js:3831
shield-study-utils: getVariation: {"name":"captive-portal","weight":1} api.js:3739
shield-study-utils: about to guard studyInfoObject 
Object { activeExperimentName: "vpn-recommendation-study@shield.mozilla.org", isFirstRun: true, firstRunTimestamp: 1534874138971, variation: {…}, shieldId: "", delayInMinutes: 20159.99755 }
api.js:3519
shield-study-utils: telemetry INFO: {"activeExperimentName":"vpn-recommendation-study@shield.mozilla.org","isFirstRun":true,"firstRunTimestamp":1534874138971,"variation":{"name":"captive-portal","weight":1},"shieldId":"","delayInMinutes":20159.99755} api.js:4100
shield-study-utils: telemetry: {"version":3,"study_name":"vpn-recommendation-study@shield.mozilla.org","branch":"captive-portal","addon_version":"2.0.0","shield_version":"5.0.4","type":"shield-study-addon","data":{"attributes":{"message_type":"event","event":"study-start"}},"testing":true} api.js:4141
TypeError: handler is undefined[Learn More] ExtensionParent.jsm:1004:5
[Show/hide message details.] onboarding-session-end should pass valid session_key OnboardingTelemetry.jsm:378
process
resource://onboarding/modules/OnboardingTelemetry.jsm:378:13
initContentMessageListener/<
jar:file:///Applications/Firefox Nightly.app/Contents/Resources/browser/features/onboarding@mozilla.org.xpi!/bootstrap.js:160:11
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.
</details>

**Comment by raymak** [comment]
For now I'll close this issue since there has been significant changes to the code. Please submit a new issue if you run into the same problem.
