### ISSUE TITLE
Add UTM parameters to Shield doorhanger primary CTA

### ISSUE THREAD

**Issue by chrismore** [raymak/vpn-recommendation-shield-study#22]
This is what I am thinking about the UTM parameters to be added to the doorhanger CTA:

utm_source=firefox-browser
utm_medium=firefox-browser
utm_campaign=shield-vpn
utm_content=[trigger code]

example [trigger code]: wifi-trigger or vpn-software-trigger. 

All values for the parameters above should have no spaces and dashes instead of spaces.

**Comment by chrismore** [comment]
@raymak  any concerns on these parameters?

**Comment by chrismore** [comment]
@devinreams ^^

**Comment by chrismore** [comment]
Per a conversation with Matt Grimes, knowing the Normandy ID would be helpful to connect post-study survey responses to folks who have converted to signing up for the VPN.

**Comment by chrismore** [comment]
update:

for the utm_content values, let's use the same slugs we are using in the triggers:

captive-portal
privacy-hostname
control
catch-all
streaming-hostname

So an example full URL would be:

https://premium.firefox.com/vpn/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_campaign=shield-vpn&utm_content=captive-portal

**Comment by raymak** [comment]
@chrismore What would you like the parameter for normandy id to be called?

**Comment by chrismore** [comment]
@raymak is the normandy id a 1:1 with a profile? Have we sent that ID to a website in the past?

**Comment by raymak** [comment]
@chrismore yes it is 1:1 and we have done this before. I'm double checking again with folks to make sure it is safe.

**Comment by raymak** [comment]
@chrismore: talking to @rayborn, this seems to be more nuanced than I thought and was possible in the study I knew because the study was opt-in and it had explicit legal approval. Rob knows the context and the policies better. 

If this is something important we should have a meeting to discuss it.

**Comment by chrismore** [comment]
@raymak  Yeah, this isn't going to have that kind of opt-in and isn't required for this study. So, let's *not* add the normandy ID and make sure the UTM parameters above are all set for each of the four arms. Thanks!

**Comment by raymak** [comment]
@chrismore the only change I would like to make to the proposed parameters, is changing the campaign to shield-vpn-1, in case we have separate deployments (e.g. if we update the addon logic).
