### ISSUE TITLE
Loading the zipped version of the extension does not work properly

### ISSUE THREAD

**Issue by raymak** [raymak/vpn-recommendation-shield-study#23]
Right now unzipping the file and loading the contents directly works.

**Comment by devinreams** [comment]
Also `web-ext run` works for me now...

Confirmed by throwing `browser.experiments.vpnRecommender.fakeCaptivePortal()` in the console and it loads and showed me the doorhanger. 🤷‍♂️

**Comment by pdehaan** [comment]
This also seems to be working locally for me (although not tested very thoroughly yet):

```sh
$ npm start -- --pref=extensions.vpn-recommendation-study-1_shield_mozilla_org.test.variationName=streaming-hostname
```

Not sure if it's worth adding a handful of scripts in package.json to allow for <kbd>$ npm run branch:streaming-hostname</kbd> to sidestep whatever is forcing us to have to unzip extensions and pre-create specific flags in about:config, etc.

I could do a bit more testing locally and possibly push a PR if the code isn't too train-wreck-esque.

**Comment by raymak** [comment]
Just to clarify, web-ext run (or npm start) works with no problem, but eventually we want the whole zip file to be loaded as an add-on, so that's the main issue.

**Comment by raymak** [comment]
I now get the ```NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIXPCComponents_Utils.import] api.js:77 ``` error. api.js:77 is ```Cu.import(context.extension.getURL("privileged/vpnRecommender/Doorhanger.jsm"), this)```. I suspect this is due to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1442900).
