### ISSUE TITLE
Implement counterfactual logging

### ISSUE THREAD

**Issue by raymak** [raymak/vpn-recommendation-shield-study#42]
Per @jmccrosky. The control branch should still log if the user would have received the notification had he/she been in a treatment branch.

**Comment by jmccrosky** [comment]
Thanks Kamyar.  Just want to add that the control branch logging should
please match the throttling/limit policy of the treatment arms if possible.

**Comment by raymak** [comment]
@jmccrosky can you elaborate on that? The rate limiting is for the visible notifications that are shown to the user. Do you mean that the control branch should pretend as though when triggered real notifications are shown to users (without them actually being shown) and report accordingly? For doing so, we would need control branches for each treatment branch, because we can't mix multiple treatments in one branch without adding significant complexity to the code.

**Comment by jmccrosky** [comment]
Yeah, if we want to be able to determine if the number of promotions we
show to a user has any cumulative impact on retention/engagement, we need
to know how many times a control profile would have seen the promotion had
it been in treatment.

If possible, having the four separate control branches would be idea.  If
it's infeasible, we can live without being able to look at cumulative
effect - we can still do a binary "was exposed" vs. "wasn't exposed"
comparison.

**Comment by raymak** [comment]
I see. I understand the point. Let me think about its implementation.

**Comment by jmccrosky** [comment]
Thanks :)  I appreciate you being so helpful with this!

**Comment by raymak** [comment]
The notifications that result from triggers that are not for the branch that the user is in, now have a ```"is-shadow": "true"``` field.
