### ISSUE TITLE
Interactions that should lead to the dismissal of the panel

### ISSUE THREAD

**Issue by raymak** [raymak/vpn-recommendation-shield-study#43]

**Comment by aaronrbenson** [comment]
• Clicking the Application/Hamburger menu
• Opening a new tab/window
• Clicking on one of the buttons (Dismiss, Tell Me More)

**Comment by raymak** [comment]
In the streaming host name and privacy host name branches: the doorhanger is dismissed when switching tabs/windows. In the catch all and captive portal branches: the doorhanger is dismissed only when new tabs/windows/ are created.

**Comment by aaronrbenson** [comment]
For the **streaming-hostname** branch I don't see the doorhanger dismissing when switching tabs but it _does_ go away when opening new tabs/windows.
