### ISSUE TITLE
The bottom doorhanger buttons are wrongly labled as "Secondary" and "Primary"

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#50]
[Affected versions]:
- Nightly 64.0a1 Build ID 20181004224156

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "xpinstall.signatures.required" is set to "false" in about:config.
- "extensions.legacy.enabled" is set to "true" in about:config.
- The VPN Recommendation Shield Study addon is installed on a clean new profile.
- Be in any of the variations other than the "control" branch.

[Steps to reproduce]:
1. Open the browser and trigger the VPN doorhanger.
2. Observe the VPN doorhanger buttons.

[Expected result]:
- The buttons' strings are: "Dismiss" and "Tell Me More".

[Actual result]:
- The buttons' strings are: "Secondary" and "Primary".

[Notes]:
- Nothing happens if the buttons are clicked, the doorhanger is not dismissed nor does it redirect.
- Attached a screenshot of the issue:
![image](https://user-images.githubusercontent.com/18304511/46613125-1c0d7680-cb1b-11e8-932e-bbfc18786d04.png)

**Comment by raymak** [comment]
This is due to https://github.com/raymak/vpn-recommendation-shield-study/issues/63

**Comment by raymak** [comment]
This should be solved now.

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the issue is no longer reproducible on the latest master build on Windows 10, Mac 10.13, and Arch Linux.
