### ISSUE TITLE
[Windows] The "Don't tell me..." string is wrongly misaligned with its checkbox

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#51]
[Affected versions]:
- Nightly 64.0a1 Build ID 20181004224156

[Affected Platforms]:
- All Windows

[Prerequisites]:
- "xpinstall.signatures.required" is set to "false" in about:config.
- "extensions.legacy.enabled" is set to "true" in about:config.
- The VPN Recommendation Shield Study addon is installed on a clean new profile.
- Be in any of the variations other than the "control" branch.

[Steps to reproduce]:
1. Open the browser and trigger the VPN doorhanger.
2. Observe the VPN doorhanger checkbox and string.

[Expected result]:
- "Don't tell me about this again." string is aligned with its checkbox.

[Actual result]:
- The checkbox and string are misaligned.

[Notes]:
- Attached a screenshot of the issue:
![image](https://user-images.githubusercontent.com/18304511/46613125-1c0d7680-cb1b-11e8-932e-bbfc18786d04.png)

**Comment by raymak** [comment]
Is this still valid? I haven't been able to reproduce this recently.

**Comment by SoftVision-CiprianMuresan** [comment]
![windows misaligment](https://user-images.githubusercontent.com/18304511/47163976-bb8eee00-d2ff-11e8-9872-4d70d0ea45ed.png)

It still looks like the string could be moved up a bit more.

**Comment by raymak** [comment]
Can you check this again?

**Comment by raymak** [comment]
@aaronrbenson, can you take a look the picture above and let me know if it is a big issue in your opinion. I'm still hoping I can get it fixed in time, but would like to know if you think it should be blocking or not.

**Comment by aaronrbenson** [comment]
@raymak Not a show stopper.

**Comment by raymak** [comment]
Let's close this as a wontfix for this iteration.

**Comment by SoftVision-CiprianMuresan** [comment]
Closing as wontfix.
