### ISSUE TITLE
[Windows] The doorhanger wrongly becomes blank when the browser window is maximized

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#54]
[Affected versions]:
- Nightly 64.0a1 Build ID 20181004224156

[Affected Platforms]:
- All Windows

[Prerequisites]:
- "xpinstall.signatures.required" is set to "false" in about:config.
- "extensions.legacy.enabled" is set to "true" in about:config.
- The VPN Recommendation Shield Study addon is installed on a clean new profile.
- Be in any of the variations other than the "control" branch.

[Steps to reproduce]:
1. Open the browser and trigger the VPN doorhanger.
2. Maximize the Browser window and observe the doorhanger.

[Expected result]:
- The doorhanger is correctly rendered.

[Actual result]:
- The doorhanger is blank.

[Notes]:
- Attached a screen recording of the issue: [Link](https://drive.google.com/open?id=19VgBcvA1MPhYGCspVtn2b7s_pfsMAPrn)

**Comment by raymak** [comment]
Possibly due to https://github.com/raymak/vpn-recommendation-shield-study/issues/63

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is still reproducible with #63 merged.

**Comment by raymak** [comment]
Should be fixed now per https://github.com/raymak/vpn-recommendation-shield-study/issues/73.

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the issue is no longer reproducible on the latest master build on Windows 10.
