### ISSUE TITLE
[Mac] Extra scrollbars are wrongly displayed inside the doorhanger if scrollbars are set to always show

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#55]
[Affected versions]:
- Nightly 64.0a1 Build ID 20181004224156

[Affected Platforms]:
- All Mac

[Prerequisites]:
- "xpinstall.signatures.required" is set to "false" in about:config.
- "extensions.legacy.enabled" is set to "true" in about:config.
- The VPN Recommendation Shield Study addon is installed on a clean new profile.
- Be in any of the variations other than the "control" branch.
- Scrollbars are set to "Always" show from System Preferences -> General settings.

[Steps to reproduce]:
1. Open the browser and trigger the VPN doorhanger.
2. Observe the doorhanger.

[Expected result]:
- The doorhanger is correctly rendered.

[Actual result]:
- The doorhanger has both horizontal and vertical scrollbars displayed in it.

[Notes]:
- Attached a screenshot of the issue:
<img width="1280" alt="screen shot 2018-10-08 at 6 31 08 pm" src="https://user-images.githubusercontent.com/18304511/46618944-744b7500-cb29-11e8-8e3f-af3d642b8bb5.png">

**Comment by raymak** [comment]
This should be fixed.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest master build on the latest Nightly 64.0a1.
