### ISSUE TITLE
The doorhanger is not dismissed when switching tabs

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#56]
[Affected versions]:
- Firefox 62.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c20) addon is installed on a clean new profile.
- Be in any of the variations other than the "control" branch.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a new tab and trigger the doorhanger.
3. Switch to the previous tab and observe the behavior.

[Expected result]:
- The doorhanger is dismissed.

[Actual result]:
- The doorhanger is still displayed.

[Notes]:
- Opening a new tab dismisses the doorhanger.
- Attached a screenshot of the issue:
![doorhanger is dismissed only when a new tab is created](https://user-images.githubusercontent.com/18304511/46669810-2c842680-cbd9-11e8-987e-cab6d01be687.gif)

**Comment by raymak** [comment]
Note that per https://github.com/raymak/vpn-recommendation-shield-study/issues/43, switching tabs/windows should dismiss the panel only in the **streaming hostname** and **privacy hostname** branches. In all other cases a new tab or window has to be opened for the panel to be dismissed.

**Comment by raymak** [comment]
This should be fixed.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible with the latest master build on Windows 10, Mac 10.13, and Arch Linux x64. The **catch-all** and **captive-portal** branches have remained unchanged.
