### ISSUE TITLE
The end study survey is not triggered at add-on removal

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#58]
[Affected versions]:
- Firefox 62.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c20) addon is installed on a clean new profile.
- Be in any of the variations other than the "control" branch.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to about:addons and click the "Remove" button next to the VPN addon.
3. Observe the behavior. 

[Expected result]:
- The end study survey is triggered in a new tab.

[Actual result]:
- Nothing happens.

[Notes]:
- The issue is not reproducible if the system's time is moved more than 31 days in the future.
- Attached a screen recording of the issue:
![no survey at addon removal](https://user-images.githubusercontent.com/18304511/46675354-e46c0080-cbe6-11e8-849d-bc30d20eb597.gif)

**Comment by raymak** [comment]
This is expected behavior. We do not have a survey for when the user disables the addon or when the addon is removed by normandy. The only case where the user sees the post-study survey is after the study expires after 30 days.

**Comment by SoftVision-CiprianMuresan** [comment]
But don't we want to survey people who have chosen to opt out of the study? I believe the survey does not trigger after 30 days in this case.

**Comment by raymak** [comment]
@rayborn: I would like to have your opinion here. On the one hand it is good to have surveys for users who leave the study, especially in Firefox 62 that the study is visible in about:addons. On the other hand, we still cannot distinguish between user disabling the addon or Normandy doing it and we run a big risk of disabling the addon using Normandy to pull the study and sending everyone to the survey page. I personally think the risk is not worth it, especially because most users will not see this addon in their about:addon. What do you think?

**Comment by rayborn** [comment]
I agree @raymak  - until we can distinguish between Normandy terminations and user terminations, it's probably better to avoid surveying at that end state unless we:

1. Are absolutely sure that we won't have to pull the study early (rare)
2. Are only sampling a very small group (rare)
3. Think that surveying users with partial experienc

es has decent value (depends on study)

I don't think this study meets the above, but I'm open to hearing thoughts on 3.

**Comment by raymak** [comment]
Ok, the consensus is to not have the survey pop up when the user disables the addon. The survey will only be shown after 30 days when the study expires. Note that expiry happens on the next session restart.

**Comment by raymak** [comment]
@SoftVision-CiprianMuresan please close this bug if you have no further objections.

**Comment by SoftVision-CiprianMuresan** [comment]
No further objections, closing.
