### ISSUE TITLE
The addon is wrongly displayed on the about:addons page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#59]
[Notes]:
- More info about this can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1365349#c3).

[Affected versions]:
- Firefox 62.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c20) addon is installed on a clean new profile.
- Be in any of the variations.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to about:addons->Extensions tab and observe the page.

[Expected result]:
- The addon is not displayed in the about:addons page.

[Actual result]:
- The addon is displayed.

[Additional notes]:
- Attached a screenshot of the issue:
![image](https://user-images.githubusercontent.com/18304511/46677961-3cf1cc80-cbec-11e8-903a-c74804915bf1.png)

**Comment by SoftVision-CiprianMuresan** [comment]
This issue can only be verified with a signed build. I'll leave it open until I have a signed build and verify after that.

**Comment by raymak** [comment]
This must be fixed now.

**Comment by SoftVision-CiprianMuresan** [comment]
Yup, tested with the latest [signed build](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c30) and the add-on is no longer displayed on the latest Firefox RC build (63.0) on Windows 10 x64, Mac 10.13, and Arch Linux x64.
