### ISSUE TITLE
[captive-portal] The doorhanger can wrongly take more than ~10 seconds to appear

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#61]
[Affected versions]:
- Firefox 62.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c20) addon is installed on a clean new profile.
- Be in the "captive-portal" variant.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and go to about:debugging.
2. Check the "Enable add-on debugging" checkbox
3. Click on the "Debug" button right below the extension name
4. Go to the "Console" section and enter browser.experiments.vpnRecommender.fakeCaptivePortal().
5. Press Enter and refocus the browser window.
6. Observe the behavior.

[Expected result]:
- A new tab is opened and the doorhanger is displayed.

[Actual result]:
- The doorhanger appears after ~10 seconds.

[Notes]:
- The doorhanger's header is not "It appears you are browsing on an unsecured wireless network.".
- Attached a screen recording of the issue: [Link](https://drive.google.com/open?id=1q3CNhFO78D5JelSjAWvDk4Zz6BI3AGr7)

**Comment by raymak** [comment]
This is expected behavior. Since it usually takes the user some time to successfully log into the captive portal, the addon polls every 10 seconds (up to 2 minutes) to check if the user is connected to the internet, and the doorhanger is shown only if the user is connected to the internet.

**Comment by SoftVision-CiprianMuresan** [comment]
Closing as Invalid.
