### ISSUE TITLE
There is an extra white line under the two doorhanger buttons

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#62]
[Affected versions]:
- Firefox 62.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c20) addon is installed on a clean new profile.
- Be in any of the variations other than the "control" branch.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Trigger the doorhanger and hover it.
3. Scroll down the doorhanger and observe the bottom part.

[Expected result]:
- The two buttons are rendered correctly.

[Actual result]:
- There is an extra white line under the two buttons.

[Notes]:
- Attached a screenshot of the issue: 
<img width="1280" alt="screen shot 2018-10-11 at 6 07 16 pm" src="https://user-images.githubusercontent.com/18304511/46816857-81b16b00-cd86-11e8-9937-97e2763ad4c4.png">

**Comment by raymak** [comment]
Should be fixed now.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest master build on the latest Nightly 64.0a1.
