### ISSUE TITLE
[catch-all] The doorhanger is not displayed a second time during the same session

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#65]
[Affected versions]:
- Firefox 62.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c20) addon is installed on a clean new profile.
- Be in the "catch-all" variant.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Wait 10 minutes and dismiss the doorhanger.
3. Move the system time forward 1 day and 1 hour.
4. Refocus the browser and wait 10 more minutes.
5. Observe the behavior.

[Expected result]:
- The doorhanger is triggered.

[Actual result]:
- The doorhanger is not displayed.

[Notes]:
- The doorhanger is triggered a second time only if the browser is restarted.
- If the same scenario is followed on the "privacy-hostname", "streaming-hostname", and "captive-portal" variants, the doorhanger is triggered on their respective pages.

**Comment by raymak** [comment]
This is expected behavior.

**Comment by SoftVision-CiprianMuresan** [comment]
Closing as Invalid.
