### ISSUE TITLE
[Windows][Intermittent] The doorhanger is sometimes not dismissed when the Firefox menu is clicked

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#66]
[Affected versions]:
- Firefox 62.0 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c20) addon is installed on a clean new profile.
- Be in any of the variations other than the "control" branch.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a new tab and trigger the doorhanger.
3. Click the Firefox menu button and observe the behavior.

[Expected result]:
- The doorhanger is dismissed.

[Actual result]:
- The doorhanger is still displayed under the Firefox menu.

[Notes]:
- Attached a screenshot of the issue:
![img_12102018_124207_0](https://user-images.githubusercontent.com/18304511/46874259-69eaed00-ce41-11e8-8b8f-32ae601a298b.png)

**Comment by raymak** [comment]
This must be fixed now.

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the issue is no longer reproducible on the latest master build on Windows 10.
