### ISSUE TITLE
The "...dontShowChecked" pref is not created when the checkbox is checked

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#67]
[Affected versions]:
- Firefox 62.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c20) addon is installed on a clean new profile.
- Be in any of the variations other than the "control" branch.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a new tab and trigger the doorhanger.
3. Click the "Don't tell me about this again" checkbox.
4. Navigate to about:config and accept the risk.
5. Search for "extensions.vpn-recommendation-study-1_shield_mozilla_org.dontShowChecked" and observe the results.

[Expected result]:
- One result is shown.

[Actual result]:
- No results are found.

[Notes]:
- Attached a screen recording of the issue:
![pref not created when checkbox is checked](https://user-images.githubusercontent.com/18304511/46874800-ac60f980-ce42-11e8-8e69-57878c161276.gif)

**Comment by raymak** [comment]
This is due to https://github.com/raymak/vpn-recommendation-shield-study/issues/63

**Comment by SoftVision-CiprianMuresan** [comment]
I was afraid of that

**Comment by raymak** [comment]
This should be fixed now.

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the issue is no longer reproducible on the latest master build on Windows 10, Mac 10.13, and Arch Linux.
