### ISSUE TITLE
The doorhanger does not redirect on Firefox Release 62.0.3

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#76]
[Notes]:
- The issue is **ONLY** reproducible on Firefox Release 62.0.
- The issue is not reproducible on Firefox 63.0 RC build or on the latest Nightly build.

[Affected versions]:
- Firefox 62.0.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c36) addon is installed on a clean new profile.
- Be in any variant except "control".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Trigger the doorhanger and click the "Tell Me More" button.
3. Observe the behavior.

[Expected result]:
- You are redirected to the VPN landing page.

[Actual result]:
- The doorhanger is dismissed and nothing happens.

[Additional Notes]:
- The issue is also reproducible with the "Why am I seeing this" button.
- Attached a screen recording of the issue:
![doorhanger does not redirect on 62 release](https://user-images.githubusercontent.com/18304511/47291116-29425f00-d60b-11e8-9150-af4070b5a3ae.gif)

- Attached a screenshot of the error displayed in the Browser Console:
![image](https://user-images.githubusercontent.com/18304511/47291114-26e00500-d60b-11e8-89bc-feacc520e2e3.png)

**Comment by SoftVision-CiprianMuresan** [comment]
After discussing this during the call, I've searched for a regression window for this issue:

 7:27.53 INFO: First good revision: 6f3907a1da34a62133832dc981e9005ee30e9388
 7:27.53 INFO: Last bad revision: e17409c5199c0ade0de9899782d6a9f5f4970871
 7:27.53 INFO: Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=e17409c5199c0ade0de9899782d6a9f5f4970871&tochange=6f3907a1da34a62133832dc981e9005ee30e9388

It looks like [bug 1362034](https://bugzilla.mozilla.org/show_bug.cgi?id=1362034) has implemented what we needed for this to work.

**Comment by raymak** [comment]
This should be fixed now.

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the issue is no longer reproducible on Firefox 62.0.3 with the [latest signed build](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c40) on Windows 10 x64, Mac 10.13.3, and Arch Linux.
